### ISSUE TITLE
Bug fixes and recommendations - master 24-10-2018

### ISSUE THREAD

**Issue by SoepThe1** [Jessasyn/Query#4]
The first three points are bug reports, after that it's all recommendations. 

- Can't always use "(return)" when deleting entries! This is what it said: 

Enter the number of the question you want to remove.
(return)
Traceback (most recent call last):
  File "Query.py", line 144, in <module>
    backbone.backbone()
  File "C:\Users\David Feenstra\Desktop\Query\master\scripts_query\backbone.py",
 line 65, in backbone
    exitvaluecheck(exitvalue)
  File "C:\Users\David Feenstra\Desktop\Query\master\scripts_query\backbone.py",
 line 41, in exitvaluecheck
    editlist.editlist()
  File "C:\Users\David Feenstra\Desktop\Query\master\scripts_query\editlist.py",
 line 189, in editlist
    linenum = delentry(cnt,listname,linenum)
  File "C:\Users\David Feenstra\Desktop\Query\master\scripts_query\editlist.py",
 line 36, in delentry
    linenum = int(linenum)
ValueError: invalid literal for int() with base 10: '(return)'

C:\Users\David Feenstra\Desktop\Query\master>pause
Press any key to continue . . .

(It did however seem to have executed the deletion of the question I had wanted to delete. It seems that this error only shows up when really having deleted something, after asking it to delete a question that isn't there, (I asked to delete question 0), it did work to use "(return)") 

- When having a list with the following languages:  A;B --> After asking it to query from A to B or B to A in a fixed order, it will ask you in the correct order, but when asking to be queried from A to B or B to A in a random order it will always ask you to translate B to A 
- When being queried while having the option to make a new list of answers you didn't fill in correctly, you'll be repeatedly asked what name you want for your list of incorrect answers, even after giving a correct answer, it seems to make a list every time with the incorrect answers you've made till then 

- You can't get back to the main menu when being queried, you either have to finish the full list or you have to restart the program 
- When in a list in the delete entry menu, you can't go back to the menu before having deleted a question 
- There should be version numbers for each master version to help categorizing the bug reports (Alpha 1, 1.1 or 2, Beta 1, 1.1... and so on..) 
- You shouldn't have to type 'enter' between entering words to continue making your list 
- You should be able to make maps for your lists. For example Engels: H7, H6.... Duits: H3, H4... and so on 
- After removing a list (or doing any other editing) you shouldn't go back to the main menu but back into the menu from which you were working 
- When editing a question, it asks for the question and answer, not for language [A] and language [B] 
- You should be able to skip the message that you're answer was wrong by pressing enter again, it should also show for long by default (I think about 3 times as long) 
- It shouldn't show .query after the name (when asking you which list, when showing you the lists or when telling you what mark you had for a list, it should never show it) 
- It should record what mark you had for what list, how long you took to make the list and keep the history of this somewhere 
- If there's just one list, it should always automatically go to that one (whatever thing you want to do with it)

**Comment by Jessasyn** [comment]
> ValueError: invalid literal for int() with base 10:  '(return)'
Shouldnt happen as editlist does this: `check = input()
    return check`
You attempted to do (return) when you were prompted to give an entry number. This isn't a bug but a missing feature.

**Comment by SoepThe1** [comment]
It should still be possible to get out of the delete entry without really deleting anything, imagine this: someone clicks on a wrong key by accident..

**Comment by Jessasyn** [comment]
Most bug fixes done, will look to the storing of list results later.
