### ISSUE TITLE
Additional bug reports and recommendations - master 24-10-2018

### ISSUE THREAD

**Issue by SoepThe1** [Jessasyn/Query#5]
- One should be able to edit the name of a list 
- When making a list and pressing enter without entering a word for one of the languages, it stops and goes back to the main menu, after saying you should not leave it empty it should just stay there 
- It seems that it doesn't always work to use "(return)" after having deleted a not existent entry, it's still a vague problem to me.. 

- Even though you didn't select the option to make a new list of things you answered wrongly, it should show which things you didn't know at the end of a query 
- It should ask you whether it's going to be sensitive to caps or punctuation 

Important: it's very likely some of these bugs are due to the fact I've got to start the script with a .bat file!

**Comment by Jessasyn** [comment]
Return bug fixed, writelan fixed, rest either discarded or taken into todolist.
