### ISSUE TITLE
Bug fixes and recommendations - master 28-10-2018

### ISSUE THREAD

**Issue by SoepThe1** [Jessasyn/Query#6]
- Can't go back to menu when not having added a question in add-question mode 
- Querying in random order still doesn't seem to work properly (see older bug list) 
- Storing lists of false answers seems to be fixed, thanks!

**Comment by Jessasyn** [comment]
please add the options you chose to query ( as in 1,1,2 or 2,2,1 ) without those, i cannot see where the issue is.

**Comment by Jessasyn** [comment]
Return bug fixed, 
query not querying in random order needs conforming (as in showing options)
