### ISSUE TITLE
Bug reports and recommendations - master 13-11-2018

### ISSUE THREAD

**Issue by SoepThe1** [Jessasyn/Query#7]
Some new bugs!: 

- In the delete list menu in edit list (3, 3) it asks to "Enter the name of the list you want to edit.", it should ask: "Enter the name of the list you want to delete." 
- It should round down the percentage when giving you a score, so you won't get something like this: "This gives you a score of 81.81818181818183%." It should be: "This gives you a score of 82%." 
- There should be a way to enter multiple synonyms for one word 
- There are still some bugs with querying and the right language being asked in random and fixed order, this is too complicated to write down understandably and should be demonstrated to you directly (it seems when querying in random order (4, 2, 1/2) it asks the wrong way around and when querying in fixed order (4, 1, 1/2) it asks the right way around but uses the wrong language in the question (for example: "what is fiets in Nederlands?") 
- When editing lists at the end of the list, the last question can become piled on op of the first before last, this should also be demonstrated to you directly 
- In the viewresult module only the first name of a result has the ".result" removed from the name, the rest are once again called "[name].result" 
- It doesn't store multiple results for one list (it seems to remember the date and time you were doing the list for the first time but then overwriting the results itself), it should make a new result file

**Comment by Jessasyn** [comment]
rounding down will be added in gui,
editlist will be altered in gui,
synonyms might be added, will be difficult,
i will be looking at bug in editlist, querylist and viewresult,
multiple storing of results will be added in gui.

**Comment by Jessasyn** [comment]
bug in querylist fixed, i tried to compensate for the switching of lanA and lanB twice, which made the solution not work at all.

**Comment by Jessasyn** [comment]
bug in viewresults fixed, indentation error caused for loop to return after one iteration.

**Comment by Jessasyn** [comment]
bug in editlist fixed, didn't write newline in alterations function.
